version: '3.1'

services:
  db:
    image: mysql
    container_name: leetcode-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: leetcode-db
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - leetcode-volume:/var/lib/mysql

volumes:
  leetcode-volume: